(xbindkey '("XF86MonBrightnessDown") "xbacklight -dec 10 -steps 4 -time 50")
(xbindkey '("XF86MonBrightnessUp") "xbacklight -inc 10 -steps 4 -time 50")
(xbindkey '("XF86Search") "dmenu_run")
(xbindkey '("XF86AudioLowerVolume") "amixer sset Master 5%-")
(xbindkey '("XF86AudioRaiseVolume") "amixer sset Master 5%+")
(xbindkey '("XF86AudioMute") "amixer sset Master toggle")
(xbindkey '("XF86AudioMicMute") "amixer sset Capture toggle")
(xbindkey '("Print") "scrot -u -e 'mv $f ~/desktop/scrots'")
(xbindkey '("XF86TouchpadToggle") "source ~/bin/touchpad-toggle")
